
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC01
 */
public class TPMalvinas_4 extends javax.swing.JFrame {

    /**
     * Creates new form TPMalvinas_4
     */
    public TPMalvinas_4() {
        initComponents();
        sig.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        veintiochom = new javax.swing.JButton();
        dieciochom = new javax.swing.JButton();
        dieciochoa = new javax.swing.JButton();
        sig = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\preunta-4.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 880, 215));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿EN QUE AÑO LA FLOTA ARGENTINA DESEMABARCA EN LAS ISLAS MALLVINAS?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 450, 20));

        veintiochom.setText("28 de Marzo de 1982");
        veintiochom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veintiochomMouseClicked(evt);
            }
        });
        getContentPane().add(veintiochom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 347, 880, 31));

        dieciochom.setText("18 de Marzo de 1982");
        dieciochom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dieciochomMouseClicked(evt);
            }
        });
        getContentPane().add(dieciochom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 880, 31));

        dieciochoa.setText("18 de Abril de 1982");
        dieciochoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dieciochoaMouseClicked(evt);
            }
        });
        getContentPane().add(dieciochoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 396, 880, 31));

        sig.setText("siguiente pregunta");
        sig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigMouseClicked(evt);
            }
        });
        sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigActionPerformed(evt);
            }
        });
        getContentPane().add(sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 445, 322, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\000_blanco_blanco_7000.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 430, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\malv.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sigActionPerformed

    private void dieciochomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dieciochomMouseClicked
       veintiochom.setBackground(Color.GREEN);
        dieciochoa.setBackground(Color.RED);
        dieciochom.setBackground(Color.RED);
        
        veintiochom.setEnabled(false);
       dieciochoa.setEnabled(false);
       dieciochom.setEnabled(false);
       
       sig.setEnabled(true);
    }//GEN-LAST:event_dieciochomMouseClicked

    private void veintiochomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veintiochomMouseClicked
        veintiochom.setBackground(Color.GREEN);
        dieciochoa.setBackground(Color.RED);
        dieciochom.setBackground(Color.RED);
        
        veintiochom.setEnabled(false);
       dieciochoa.setEnabled(false);
       dieciochom.setEnabled(false);
       
       sig.setEnabled(true);
       TPMalvinas.c ++; 
    }//GEN-LAST:event_veintiochomMouseClicked

    private void dieciochoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dieciochoaMouseClicked
        veintiochom.setBackground(Color.GREEN);
        dieciochoa.setBackground(Color.RED);
        dieciochom.setBackground(Color.RED);
        
        veintiochom.setEnabled(false);
       dieciochoa.setEnabled(false);
       dieciochom.setEnabled(false);
       
       sig.setEnabled(true);
    }//GEN-LAST:event_dieciochoaMouseClicked

    private void sigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigMouseClicked
        setVisible(false);
        new TPMalvinas_5().setVisible(true);
    }//GEN-LAST:event_sigMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPMalvinas_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dieciochoa;
    private javax.swing.JButton dieciochom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton sig;
    private javax.swing.JButton veintiochom;
    // End of variables declaration//GEN-END:variables
}
