
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC01
 */
public class TPMalvinas_8 extends javax.swing.JFrame {

    /**
     * Creates new form TPMalvinas_8
     */
    public TPMalvinas_8() {
        initComponents();
        sigggg.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dieciseis = new javax.swing.JButton();
        veintiseis = new javax.swing.JButton();
        veintiuno = new javax.swing.JButton();
        sigggg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\pregunta-8.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 880, 236));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿CUANDO LOS INGLESES DESEMBARCAN EN LAS ISLAS?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 440, 55));

        dieciseis.setText("16 de Mayo");
        dieciseis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dieciseisMouseClicked(evt);
            }
        });
        getContentPane().add(dieciseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 326, 880, 30));

        veintiseis.setText("26 de Mayo");
        veintiseis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veintiseisMouseClicked(evt);
            }
        });
        getContentPane().add(veintiseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 367, 880, 30));

        veintiuno.setText("21 de Mayo");
        veintiuno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veintiunoMouseClicked(evt);
            }
        });
        getContentPane().add(veintiuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 408, 880, 31));

        sigggg.setText("siguiente pregunta");
        sigggg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siggggMouseClicked(evt);
            }
        });
        getContentPane().add(sigggg, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 466, 267, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\000_blanco_blanco_7000.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 320, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\malv.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dieciseisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dieciseisMouseClicked
        veintiseis.setBackground(Color.RED);
        veintiuno.setBackground(Color.GREEN);
        dieciseis.setBackground(Color.RED);

        veintiseis.setEnabled(false);
        veintiuno.setEnabled(false);
        dieciseis.setEnabled(false);
        
        sigggg.setEnabled(true);
        
    }//GEN-LAST:event_dieciseisMouseClicked

    private void veintiseisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veintiseisMouseClicked
        veintiseis.setBackground(Color.RED);
        veintiuno.setBackground(Color.GREEN);
        dieciseis.setBackground(Color.RED);

        veintiseis.setEnabled(false);
        veintiuno.setEnabled(false);
        dieciseis.setEnabled(false);
        
        sigggg.setEnabled(true);
    }//GEN-LAST:event_veintiseisMouseClicked

    private void veintiunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veintiunoMouseClicked
        veintiseis.setBackground(Color.RED);
        veintiuno.setBackground(Color.GREEN);
        dieciseis.setBackground(Color.RED);

        veintiseis.setEnabled(false);
        veintiuno.setEnabled(false);
        dieciseis.setEnabled(false);
        sigggg.setEnabled(true);
        
        TPMalvinas.c ++; 
    }//GEN-LAST:event_veintiunoMouseClicked

    private void siggggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siggggMouseClicked
        setVisible(false);
        new TPMalvinas_9().setVisible(true);
    }//GEN-LAST:event_siggggMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPMalvinas_8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dieciseis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton sigggg;
    private javax.swing.JButton veintiseis;
    private javax.swing.JButton veintiuno;
    // End of variables declaration//GEN-END:variables
}
