
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC01
 */
public class TPMalvinas_3 extends javax.swing.JFrame {

    /**
     * Creates new form TPMalvinas_3
     */
    public TPMalvinas_3() {
        initComponents();
        SIGG.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        juan = new javax.swing.JButton();
        leopoldo = new javax.swing.JButton();
        raul = new javax.swing.JButton();
        SIGG = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        siguiente.setText("siguiente pregunta");
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
        });
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\pregunta-3.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 880, 286));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUE PRESIDENTE PROPONE RECUPERAR LAS MALVINAS?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 390, 30));

        juan.setText("Juan Carlos Onogania");
        juan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juanMousePressed(evt);
            }
        });
        juan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juanActionPerformed(evt);
            }
        });
        getContentPane().add(juan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 880, 32));

        leopoldo.setText("Leopoldo Fortunato Galtieri");
        leopoldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leopoldoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leopoldoMousePressed(evt);
            }
        });
        leopoldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leopoldoActionPerformed(evt);
            }
        });
        getContentPane().add(leopoldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 377, 880, 32));

        raul.setText("Raul Alfonsin");
        raul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raulMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                raulMousePressed(evt);
            }
        });
        getContentPane().add(raul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 463, 880, 32));

        SIGG.setText("siguiente pregunta");
        SIGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGGMouseClicked(evt);
            }
        });
        SIGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGGActionPerformed(evt);
            }
        });
        getContentPane().add(SIGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 501, 224, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\000_blanco_blanco_7000.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 370, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\malv.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juanMouseClicked
        juan.setBackground(Color.RED);
        leopoldo.setBackground(Color.GREEN);
        raul.setBackground(Color.RED);
        
       juan.setEnabled(false);
       leopoldo.setEnabled(false);
       raul.setEnabled(false);
       
        SIGG.setEnabled(true);
    }//GEN-LAST:event_juanMouseClicked

    private void juanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juanMousePressed

    }//GEN-LAST:event_juanMousePressed

    private void leopoldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leopoldoMouseClicked
        juan.setBackground(Color.RED);
        leopoldo.setBackground(Color.GREEN);
        raul.setBackground(Color.RED);
        
       juan.setEnabled(false);
       leopoldo.setEnabled(false);
       raul.setEnabled(false);
       
       SIGG.setEnabled(true);
       TPMalvinas.c ++; 
    }//GEN-LAST:event_leopoldoMouseClicked

    private void leopoldoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leopoldoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_leopoldoMousePressed

    private void raulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raulMouseClicked
        juan.setBackground(Color.RED);
        leopoldo.setBackground(Color.GREEN);
        raul.setBackground(Color.RED);
        
       juan.setEnabled(false);
       leopoldo.setEnabled(false);
       raul.setEnabled(false);
       
       SIGG.setEnabled(true);
       
    }//GEN-LAST:event_raulMouseClicked

    private void raulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raulMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_raulMousePressed

    private void leopoldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leopoldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leopoldoActionPerformed

    private void juanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juanActionPerformed

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseClicked
        
    }//GEN-LAST:event_siguienteMouseClicked

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed

    }//GEN-LAST:event_siguienteActionPerformed

    private void SIGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGGActionPerformed
        setVisible(false);
        new TPMalvinas_4().setVisible(true);
    }//GEN-LAST:event_SIGGActionPerformed

    private void SIGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGGMouseClicked
        
    }//GEN-LAST:event_SIGGMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPMalvinas_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SIGG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton juan;
    private javax.swing.JButton leopoldo;
    private javax.swing.JButton raul;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
