/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC01
 */
public class TPMalvinas_3 extends javax.swing.JFrame {

    /**
     * Creates new form TPMalvinas_3
     */
    public TPMalvinas_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        milochoveintitres = new javax.swing.JButton();
        milochoveintitres1 = new javax.swing.JButton();
        milochoveintitres2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC01\\Documents\\GitHub\\tp_islas_malvinas\\TPMalvinas\\Imagenes\\pregunta-3.png")); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUE PRESIDENTE PROPONE RECUPERAR LAS MALVINAS?");

        milochoveintitres.setText("Juan Carlos Onogania");
        milochoveintitres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                milochoveintitresMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                milochoveintitresMousePressed(evt);
            }
        });
        milochoveintitres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milochoveintitresActionPerformed(evt);
            }
        });

        milochoveintitres1.setText("Leopoldo Fortunato Galtieri");
        milochoveintitres1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                milochoveintitres1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                milochoveintitres1MousePressed(evt);
            }
        });
        milochoveintitres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milochoveintitres1ActionPerformed(evt);
            }
        });

        milochoveintitres2.setText("Raul Alfonsin");
        milochoveintitres2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                milochoveintitres2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                milochoveintitres2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addComponent(milochoveintitres1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(milochoveintitres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(milochoveintitres2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(milochoveintitres1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(milochoveintitres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(milochoveintitres2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void milochoveintitresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milochoveintitresMouseClicked
        milochoveintitres.setBackground(Color.RED);
    }//GEN-LAST:event_milochoveintitresMouseClicked

    private void milochoveintitresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milochoveintitresMousePressed

    }//GEN-LAST:event_milochoveintitresMousePressed

    private void milochoveintitres1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milochoveintitres1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_milochoveintitres1MouseClicked

    private void milochoveintitres1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milochoveintitres1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_milochoveintitres1MousePressed

    private void milochoveintitres2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milochoveintitres2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_milochoveintitres2MouseClicked

    private void milochoveintitres2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milochoveintitres2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_milochoveintitres2MousePressed

    private void milochoveintitres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milochoveintitres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milochoveintitres1ActionPerformed

    private void milochoveintitresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milochoveintitresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milochoveintitresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPMalvinas_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPMalvinas_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton milochoveintitres;
    private javax.swing.JButton milochoveintitres1;
    private javax.swing.JButton milochoveintitres2;
    // End of variables declaration//GEN-END:variables
}
